### ISSUE TITLE
City banner not updating when selecting different tiles to work.

### ISSUE THREAD

**Issue by camk16** [Azurency/CQUI_Community-Edition#10]
![untitled](https://user-images.githubusercontent.com/30790283/30147688-f6b4ec8e-935c-11e7-8492-c7d59b0529d8.png)
![sadasd](https://user-images.githubusercontent.com/30790283/30147687-f6afd44c-935c-11e7-87b5-36c5bcc675aa.png)

**Comment by Azurency** [comment]
Yes, there's indeed a bug with the current citybanner, it was fixed in 4c180a78201e94efef6f42e4eba6633f32220768 but reintroduced with the `steam sync` commit c1a682472d39ac22bdbbdbe590c19306cf399494.

In my dev branch https://github.com/Azurency/cqui/tree/summer-2017 it's working fine because I did not use the steam version as a base (I used the actual summer-2017 cqui branch) @sparrow8332 I really think we should clean that up and remove that commit purely, I will work on that now and publish a new branch with all the changes you made after `steam sync`.

**Comment by Azurency** [comment]
Should be fixed on https://github.com/Azurency/CQUI_Community-Edition/tree/cleanned-summer-2017 still need more review on that branch before replacing the actual summer-2017
