### ISSUE TITLE
Right clicking the diplo banner bypass the 10 turn waiting time when at war

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#167]
When you're at war you have to wait 10 turn before negotiating peace, but by right clicking the leader icon in the diplo banner, this waiting time is bypassed.

**Comment by ricanuck** [comment]
Yeap, old but that I didn't have the time to tackle before the Summer fiasco. Although, if I remember correctly, the bypass is ONLY for entering negotiations, but the deal will NEVER be accepted. Can you test if my memory is correct? If yes, then this is only a "pseudo-UI" bug, and not a functional one (if I remember correctly, I did not rush to fix this bug exactly because of that non-functional nature).

**Comment by ricanuck** [comment]
OK, we have two options here:
1. I modify the code so that when right clicking a leader at War, it goes to diplo view as if it were left clicked. This is the easy way.
2. Find the function to test if peace is available, which so far from my looking seems to be embedded in the dll. I might find an indirect way of testing the same, but this is the hard way.

Which one do you prefer?

**Comment by ricanuck** [comment]
Got it solved using option 2 (I like the hardest way... :rofl: ).
Will commit the code snipet after you merge the previous pull req regarding diplomacyribbon.lua...

**Comment by sparrow8332** [comment]
The hard way is always the most fun and rewarding :-)

**Comment by ricanuck** [comment]
Well, also usually the smallest in number of lines of code... the hard part is to find out HOW... in this case, after finding out a way to test it, it was only 2 lines of code...
