### ISSUE TITLE
Policy Change Reminder Appearing on Turn 1

### ISSUE THREAD

**Issue by orochi28** [Azurency/CQUI_Community-Edition#183]
Looks like the [latest update](https://github.com/Azurency/CQUI_Community-Edition/issues/152) included a policy change reminder? I somehow got it on turn 1, when there was no government or policy to choose from. When I click on "Change Government", nothing happens and the dialog box stays there, though I am able to close the dialog and end turn. See screenshot below. It was a single player game with CQUI, Civ VI Graphs, and no other mods. I run the latest patch of Civ 6 on Windows, with all current DLCs enabled. Among three games I've started since yesterday, this only happened in one game.

![policy change reminder bug](https://user-images.githubusercontent.com/33386307/32416263-371d428e-c20c-11e7-8fe5-3e9c36a2ca87.jpg)

**Comment by Azurency** [comment]
Are you using any other mod ? On windows ? Can you reproduce this issue and then post your logs (they're in `Documents\my games\Sid Meier's Civilization VI\Logs`) and if it's possible your save game.

**Comment by orochi28** [comment]
Updated description with more info. Unfortunately I didn't save that turn, but I'll try to reproduce this issue.

**Comment by orochi28** [comment]
@Azurency I just encountered this bug again. Still on Windows but with more mods: CQUI, Civ VI Graphs, RevealMap, Flatter Dynamic Turn Timer, and Greater Start Distance.

Attached the log files and the save game. Hope this helps!

![policy change reminder bug 2](https://user-images.githubusercontent.com/33386307/32477534-a3527206-c344-11e7-9775-13d76e834b91.jpg)

**Comment by oerms** [comment]
@sparrow8332 I think it only occurs in turn 1 (when founding the city right away?).

**Comment by sparrow8332** [comment]
ive ran another 6 games from turn 1 to turn 15 and still not having the issue you describe

**Comment by orochi28** [comment]
It only happens on turn 1, and only in some games. I've seen it happen with only CQUI and Civ VI Graphs, so it may be possible that this bug is caused by the two mods being incompatible with each other. I'll see if I can reproduce it in CQUI only. If I can't do so within a few days, we can just close this ticket.

**Comment by orochi28** [comment]
Update: I played a dozen starts after unsubscribing from Civ VI Graphs, and this issue never occurred again. Pretty sure it's a mod incompatibility issue and not a bug in CQUI.

**Comment by tylerforsythe** [comment]
Reliably duplicated!

I realize this is old, but in case anyone else finds this, I just experienced this a whole 2.5 years later. This is my first game ever using this mod. The only other mod I have is [Aircraft Carriers Double Capacity](https://steamcommunity.com/sharedfiles/filedetails/?id=1201390784). I am subscribed to this mod via Steam Workshop -- I did not attempt to install it any other way.

The only reason I'm posting a comment here is because I noticed that the other player above is playing as Frederick Barboarossa, which is also who I am playing as when this happened. I do _not_ get a prompt that I can close -- it completely halts progress of the game. I cannot progress to the next turn.

Screenshot and saved game file attached. Reloading the save puts me right back into the same "stuck" spot.

I had my Create Game settings saved, so I tested 3 other leaders by loading my settings, changing the leader, and immediately beginning.
✅  Montezuma, no problem.
✅  Gilgamesh, no problem.
✅  John Curtin, no problem.

Tried again with a new Frederick, and exact same issue occurred. It appears the bug is this mod + Frederick leader.
❌  Frederick Barboarossa

I do _not_ own Gathering Storm or Rise and Fall.

![Screenshot 2020-04-16 21 45 15](https://user-images.githubusercontent.com/1689004/79530158-cd07a200-802b-11ea-936c-2ffb28eb1860.png)

[Fred 4000 BC  Civics Bug.zip](https://github.com/Azurency/CQUI_Community-Edition/files/4490820/Fred.4000.BC.Civics.Bug.zip)
