### ISSUE TITLE
Question: How is the city screen lens overlay?

### ISSUE THREAD

**Issue by astog** [Azurency/CQUI_Community-Edition#20]
I have been curious about this for a while, how do people feel about the hex highlighting in the city screen (or during hover). The hex highlighting basically shows the worked and locked tiles. I added this in ML Summer Update, but have not heard any feedback. Do most people just disable it? How would you like me to improve on that? Like a delay on the hover?

_I would post this in my repo, but this has more active users..._

**Comment by sparrow8332** [comment]
I disable it but only because i get confused and thats not hard for me lol i think its just a case off getting use to it tbh. Great idea though :-)

**Comment by camk16** [comment]
I like it a lot. I remember when it was first mentioned not very long before the summer patch hit, which obviously broke CQUI and thus delayed the overlay's implementation. Once you get used to it, it's a much quicker and more efficient means to quickly view which tiles are being worked. One thing I noticed, though, is that when you hover over a city banner you get the black outline from every city in view -- not just the city you're hovering over. Not sure if that was intentional or not, but to me it seems unnecessary. Nevertheless, it by no means is a pressing issue, only a "just saying" type of thing -- absolutely no need to make it a priority.

**Comment by BlackSmokeDMax** [comment]
I mostly like the lens overlay how it is currently. The only thing I'd like to see differently is perhaps having the city's Districts highlighted in some way, to make them easy to spot on the map while in City viewing mode. (maybe even when not in city  viewing mode as well, but I suppose that would just be a regular lens update/addon at that point)

**Comment by Azurency** [comment]
I also like the new highlighting but like @camk16 I think it's disturbing that when you hover a city you have black outline for every other city and not the one you're hovering only.

But other than that, great work 😉

**Comment by astog** [comment]
The black outline is the side-affect of using the government lens to implement it. I need to manually color them "transparent" (which gives them a black outline). Might switch this out with the normal lens highlighting. Thanks for the feedback everyone!
