### ISSUE TITLE
Project That Is No Longer Possible To Produce Remains In The Production Queue

### ISSUE THREAD

**Issue by datbunneh** [Azurency/CQUI_Community-Edition#220]
**Current Behavior:**
Project that is no longer possible to produce remains in the production queue.

**Expected Behavior:**
Project that is no longer possible to produce is removed from the production queue.

**Steps To Reproduce:**
1. Start building some building in any specialized district.
2. Wait until some enemy unit occupies this district.
3. Notice the following:
3.1. You are proposed to select a new project for the city. **[Okay]**
3.2. Right side of city plate contains a cogwheel indicating that there is no active project. **[Okay]**
3.3. When you open city screen you still see the previous project that is no longer possible to complete in the queue. **[Not Okay]**
3.4. After you select another project you will have to cancel the previous one (as it still remains in the queue) before the city will actually start producing anything. If you don't cancel the previous one and exit city screen you will be still proposed to choose a project for this city. **[Not Okay]**

**Comment by Azurency** [comment]
Related to #112

**Comment by OmnipotentStomper** [comment]
Related problem. City has Ancient Walls that are partially damaged.
Medieval Walls show in production queue.
When removed from queue, Medieval Walls say they can't be built because they require Ancient Walls.
Ancient Walls don't show up in production panel as needing repair.

See SHAR-I QUMIS and GORDIAN (Two Western Persian cities) in the following save game.
[CYRUS 156 900 AD.Civ6Save.zip](https://github.com/Azurency/CQUI_Community-Edition/files/1509837/CYRUS.156.900.AD.Civ6Save.zip)
