### ISSUE TITLE
Movement/Camera issue with CQUI after todays civ 6 patch (1.0.0.216)

### ISSUE THREAD

**Issue by xyron1** [Azurency/CQUI_Community-Edition#276]
Like mentioned in the title, since the recent civ 6 patch CQUI seems to have trouble by using unit movement (right click does not work for unit movement anymore) or using the camera movement like usually.

Spoken by that civ 6 is kinda horrible to play without a fully functional CQUI overhaul. Hopefully you guys find the time and effort to fix those issues in the near future. Thanks a lot for your tremendous work on this project, it is a MUST HAVE (probably the best) civ 6 mod imo. 

Many thanks in advance!

**Comment by steveshotz** [comment]
I too am having this issue. Additionally, when I disable the mod in the additional content screen, the game still doesn't work. Cities do not have their names overhead and there is no city management. Otherwise, the movement and camera works though.

**Comment by eporres** [comment]
I have also experienced camera issues. From the little bit I can tell, the issue seems to be the screen edge panning. Once I comment out the event handlers related to panning, I am able to click and move the camera again. Unfortunately, I just recently started contributing, so I don't really have a solution for this yet. A more experienced contributor might be able to tackle this more quickly.

**Comment by xyron1** [comment]
@steveshotz just disable CQUI completly (if you use steam -> just unsubscribe for now) or if you had manual downloaded CQUI into your mods folder (just copy/paste it elsewhere) should fix your discribed problem for now.

**Comment by HgOne** [comment]
I experience the same issue.
It is hard to go back to the base UI 
Thanks for the great MOD!

**Comment by Azurency** [comment]
see #283
