### ISSUE TITLE
Mac:  Unable to place districts on the map

### ISSUE THREAD

**Issue by irishbs** [Azurency/CQUI_Community-Edition#296]
After the latest stream update for MAC the CQUI is unable to place districts on the map.  I am able to select the district but it will not click on the map and place the district.

Mac 
Aspry  v1.0.7 bld.update 1.0.0.194

**Comment by JCron245** [comment]
The CQUI team is currently working to make CQUI compatible with the latest update to the base game, and then compatible with R&F enabled. It sounds like your problem is related to that, they have an open issue for this at https://github.com/Azurency/CQUI_Community-Edition/issues/283, you should post your issue there if someone hasn't already posted about it.

**Comment by kerrizor** [comment]
There are instructions in the README specific for macs, I believe.

**Comment by blaskey** [comment]
I believe the mac/linux instructions in the README are out of date. Mac/Linux are running the fall update now. So I think the current HEAD of this repo will work. Trying it out tonight. I can verify, trying to run the version of CQUI for the summer update on 1.0.0.194 breaks placing districts and you can't open the civics tree.

**Comment by Lasconik** [comment]
+1, but I'm on Windows. And cannot place wonders too (I checked the requirements). As it is a separate problem I will open a new issue

**Comment by nikayou** [comment]
For those who still have troubles with this: check that the other mod "production queue" is disabled. When I did that, the game was working fully again (except for the tech tree)
