### ISSUE TITLE
How to toggle city details panel?

### ISSUE THREAD

**Issue by michel233** [Azurency/CQUI_Community-Edition#305]
Please i am finding it hard to toggle city details panel,please help me.Thank you

**Comment by figar3** [comment]
I have the same problem.  It seems to be a bug.

06.03.2018 7:18 AM "michel233" <notifications@github.com> napisał(a):

Please i am finding it hard to toggle city details panel,please help
me.Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azurency/CQUI_Community-Edition/issues/305>, or mute
the thread

**Comment by Azurency** [comment]
What do you mean by "finding it hard" ? You just need to click on a city.
Are you on windows with the base game only and without the Rise and Fall expansion enabled ?

**Comment by michel233** [comment]
yes i am on windows with rise and fall enabled sir
