### ISSUE TITLE
Tech & Culture Trees

### ISSUE THREAD

**Issue by QuiSuisMoi** [Azurency/CQUI_Community-Edition#310]
Tech and Culture Trees aren't showing up, can't even open the tech tree.

**Comment by oerms** [comment]
CQUI is not compatible with Rise and Fall yet.

**Comment by alexeyOnGitHub** [comment]
I see overall CQUI has made a lot of progress in supporting RiseAndFall version.

with the latest Civ6 version + CQUI I can select techs and civics in trees, but on-screen windows with tech and civic names (and their progress) are empty. they show "Turns: 33" and "Research name" instead of actual name.

**Comment by kuboshit12** [comment]
There are missing files in CQUI_Community-Edition-master\Assets\UI\Screens. Just copy TechTree and TechTree.lua from base game Base\Assets\UI\Screens and it should fix the problem. If you're still missing civics tree, copy CivicsTree and CivicsTree.lua.

**Comment by FRUM10US** [comment]
I have exactly same issue as you, alexeyOnGitHub... Did you get a fix for this ??

**Comment by alexeyOnGitHub** [comment]
the latest CQUI "expansion1" branch works fine, for the most part. don't forget to delete old versions of that mod from your disk and also start a new game.

**Comment by Azurency** [comment]
see #283
