### ISSUE TITLE
Spring 2018 update (1.0.0.257)

### ISSUE THREAD

**Issue by Azurency** [Azurency/CQUI_Community-Edition#331]
So we haven't finish to fully update the mod [for the Rise and Fall expansion](https://github.com/Azurency/CQUI_Community-Edition/issues/283) and already another patch is pushed by Firaxis.

#### 🤔 About the Rise and Fall issue
I created this new issue even though [the other one](https://github.com/Azurency/CQUI_Community-Edition/issues/283) is not closed because I don't want to clutter the already cluttered Rise and Fall issue.
The priority will be to fix the base game version first and then hopefully finally finish updating cqui for R&F.

#### 🔨 How we'll proceed

We'll try to (roughly) follow these steps, maybe not in that exact order : 
- [x] Make the UI files diff of the base game patch and have a quick look at them
- [x] Make a list of which files in the mod need to be looked at for the base game
- [x] Create a new `Patch-1.0.0.257` branch
- [x] Patch the changes for CQUI _(the hard work)_
- [x] Look at the integrations of CQUI, maybe they already have patched on their end
- [x] Patch the changes for the integrations _(also not easy)_
- [x] Test the changes
- [x] Go back to the update for Rise and Fall issue

#### 💪 Helping cqui
You may have noticed that it's taking me a lot of time for me to finish the update for Rise and Fall, review issues, test the pull requests and answer everybody. It's because I'm very busy with work at the moment, I try to find as much time as I can to dedicate to this mod but sometime it's just not enough.

**If you're a developer** that know how to use git and GitHub (the PRs), you can help this mod ! I'll soon put a list of files that need to be changed, it's "just" merging the changes introduced by the update to the cqui files (and being careful not to remove/change any cqui feature along the way) by reviewing the diffs.

**I want to help but I'm not a developer** if you have time to spare to help cqui, we still need people to answers on GitHub, Steam and discord, moderate and label the issues on GitHub, ... You can [join the discord](https://discord.gg/CXXAYW6) and post a message there.

**Comment by Azurency** [comment]
Here are the diffs : https://github.com/Azurency/Civ6-UIFiles/commit/ad103891208f1dfab5acc3bd16a690453fab06f1.
About **35 files changed** (it says a lot more on GitHub because there're some encoding change that are not relevant).
I'll make a list of what needs to be looked at now.

**Comment by Azurency** [comment]
The list of files to change : 

#### CQUI changes

- [ ] `actionpanel.lua`, very few changes - _easy_
- [x] `citysupport.lua`, two lines - _easy_
- [x] `civ6common.lua`, one if - _easy_
- [x] `diplomacyactionview.lua`, one line - _easy_
- [x] `ingame.lua`, one line - _easy_
- [ ] `panels/citypaneloverview.lua`, few changes - _easy_
- [ ] `panels/citypaneloverview.xml`, few changes - _easy_
- [ ] `panels/notificationpanel.lua`, some new things - _easy_
- [ ] `partialscreenhooks.lua`, few changes - _easy_
- [ ] `popups/techciviccompletedpopup.lua`, some changes - _should be easy_
- [x] `screens/governmentscreen.lua`, one line - _easy_
- [ ] `screens/techtree.lua`, some changes - _require some work_
- [ ] `unitflagmanager.lua`, few changes - _easy_
- [ ] `worldview/citybannermanager.xml`, three changes - _easy_

#### Integrations changes

BES :
- [ ] `choosers/espionagechooser.lua`, two lines - _easy_
- [ ] `choosers/espionagechooser.xml`, some changes - _require some work_
- [ ] `espionagesupport.lua`, some changes - _require some work_

BTS :
- [ ] `choosers/traderoutechooser.xml`, some changes - _require some work_

IDS _(it's maintained by CQUI)_ : 
- [ ] `diplomacydealview.lua`, lots of changes - _require work_

You can contribute by opening pull request on the `Patch-1.0.0.257` branch, also for coordination purposes, join the discord and tell us what you're doing ;)

**Comment by pspjuth** [comment]
techtree.lua has a fix here: #329

**Comment by Azurency** [comment]
Great, thanks to the contributors the cqui part is done 🎉, now we need to move on to the integrations.

#### About the integrations
As I don't know is @astog is going to update BES and BTS quickly, we'll make the changes and create a pull request in here **and in his repos also**.

**Comment by Azurency** [comment]
So everything is updated but `diplomacydealview.lua` need to be tested for the new third party war, I think it might not work as it is. We'll need to implement that. (I don't have time to test right now, I'll try as soon as I can).

**Comment by MarkusKV** [comment]
So, I thought I'd try this branch against 1.0.0.257 with R&F ruleset.  It's not really working.  Tech and Civics are not displayed in the upper right.  I went back to expansion1 (with the techtree fix) and its working with 1.0.0.257 with R&F ruleset.  Am I missing something?  Am I thick?

I downloaded the zip of this branch rather than cloning.

**Comment by NoShotz** [comment]
This isn't updated for R&F yet

**Comment by MarkusKV** [comment]
Thanks. I'll go back to expansion1.  Seems to work for everything I've done so far.

**Comment by rasputinoz** [comment]
hopefully they get back to RF fixes if this is now done. seem to be finding more bugs in RF even with the expansion and Techtree loaded.
IE. Citystate envoy screen not working.

**Comment by alexeyOnGitHub** [comment]
@MarkusKV is "expansion1" branch working fine for you even with 1.0.0.257 RaF version?

**Comment by MarkusKV** [comment]
@alexeyOnGitHub Yes.  It's working.

**Comment by camk16** [comment]
Tech tree doesn't open

**Comment by MarkusKV** [comment]
You need the tech tree patch. Look for a zip file somewhere up in this thread. Or in the extension1 thread. 


Regards. Mark K Vallevand 


-------- Original message --------From: camk16 <notifications@github.com> Date: 5/28/18  11:31 AM  (GMT-06:00) To: Azurency/CQUI_Community-Edition <CQUI_Community-Edition@noreply.github.com> Cc: MarkusKV <mvallevand@q.com>, Mention <mention@noreply.github.com> Subject: Re: [Azurency/CQUI_Community-Edition] Spring 2018 update (1.0.0.257)
  (#331) 
Tech tree doesn't open

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Azurency/CQUI_Community-Edition/issues/331#issuecomment-392566500","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/331#issuecomment-392566500","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azurency/CQUI_Community-Edition","title":"Azurency/CQUI_Community-Edition","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Azurency/CQUI_Community-Edition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@camk16 in #331: Tech tree doesn't open"}],"action":{"name":"View Issue","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/331#issuecomment-392566500"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [Azurency/CQUI_Community-Edition] Spring 2018 update (1.0.0.257) (#331)",
"sections": [
{
"text": "",
"activityTitle": "**camk16**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@camk16",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Azurency/CQUI_Community-Edition\",\n\"issueId\": 331,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Azurency/CQUI_Community-Edition\",\n\"issueId\": 331\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Azurency/CQUI_Community-Edition/issues/331#issuecomment-392566500"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 334501495\n}"
}
],
"themeColor": "26292E"
}

**Comment by alexeyOnGitHub** [comment]
thank you for the info, @MarkusKV .
I found that patch here https://github.com/Azurency/CQUI_Community-Edition/issues/329#issuecomment-388280198
downloaded techtree.zip file, unpacked, copied the lua script to 

> <user>\Documents\My Games\Sid Meier's Civilization VI\Mods\CQUI_Community-Edition-expansion1\Assets\UI\Screens\techtree.lua

now the tech tree is working fine.

**Comment by rasputinoz** [comment]
Reason being is they busy fixing the mod. This is a work around until finalised .

Thanks guys for great work

Sent from my iPhone

On 29 May 2018, at 4:51 am, camk16 <notifications@github.com<mailto:notifications@github.com>> wrote:


@MarkusKV<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarkusKV&data=02%7C01%7C%7Cc586b9fe79c14ca1220a08d5c4d03e35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636631321029063923&sdata=veYmUMcdRx8VWhh2R21oM6btvO31vjb0C98Yr9J162A%3D&reserved=0> @alexeyOnGitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FalexeyOnGitHub&data=02%7C01%7C%7Cc586b9fe79c14ca1220a08d5c4d03e35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636631321029063923&sdata=lEIwIi8ecaAy6VDgh7TVN7PAJcIvWnQkg%2FYGb%2BofEag%3D&reserved=0> - Awesome! Thank you both! I'm curious, though, as to why this file wouldn't just be merged into the expansion1 branch? You know, instead of creating a need to add it manually. Seems a bit odd.

**Comment by ComanDanteDevOps** [comment]
Any updates?

**Comment by kriscamilleri** [comment]
Any eta on the new update?

Thanks for all the great work :)

**Comment by ihendriks** [comment]
No ETA. Don't know when Azurency will be available.

**Comment by StevenStone1701** [comment]
for those who found that last update just (again) cqui breaking. there is a trick to return to an earlier version of civ VI. tested it myself and coun't beleave that it actually worked... apparently steam holts records of every update from every game on some server. you just have to follow the instructions of this reddit page(it talkes about fallout 4 with the same principle/problem):https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/. for the record, I do not advertise or want to do that by any means. it just a trick I use for a while when a brand new update comes out

**Comment by wayneb64** [comment]
So version 262 breaks CQUI again? It sounded like all they did was remove Red something or other and add some multiplayer changes. Everything was working for me accept joint war which I don't really use so I am not at the latest un-merged stuff.

**Comment by Azurency** [comment]
Ok, the IDS is working for the base game now, the work here is done. Let's get back to the Rise and Fall issue.
