### ISSUE TITLE
Envoy Not Moving to City-State

### ISSUE THREAD

**Issue by ironstorm613** [Azurency/CQUI_Community-Edition#349]
I just recently started using this version of CQUI (I took a break from Civ VI for a bit after Rise & Fall launch) and all around it's a great mod. The World Tracker issue seems to have been posted already, but another one I noticed is when I go to send an envoy to a city-state, I can click the number as much as I want and it will not move off 0. Not sure if others are having the issue.

**Comment by rasputinoz** [comment]
this seems to be an issue with Rise and fall only usually. If you are using the RF version of civ 6 you need to download the Expansion1 version from GitHub instead of the master version

You will also need to find the thread on here for a fix to the Tech and civics not working and download the new techtree.lua

**Comment by ironstorm613** [comment]
Alright I'll give this a shot tonight when I get home and update after. Thank you!

**Comment by ihendriks** [comment]
Keep in mind that if you download and install the mod manually you'll have to get rid of the workshop version (unsubscribe completely) and make sure the files are gone. Otherwise you'll run into all sorts of funky issues. Also note that the `expansion1` branch is only partially functional and might throw some other issues your way.

The `Patch-1.0.0.257` branch is more functional, but doesn't work well with Rise & Fall. So if you run into issues with `expansion1`, maybe you can try the other one and play without the expansion.

Sorry for the inconvenience.

**Comment by ironstorm613** [comment]
This is going to turn out to be a busy night to see if this works then! Worth a shot

**Comment by mithlug** [comment]
You can also look at #321 to see how to disable envoy part of cqui

**Comment by Azurency** [comment]
see #283
