### ISSUE TITLE
Finish wonder in Multiplay Mode, can`t disable wonder cinematics

### ISSUE THREAD

**Issue by Gladosxiao** [Azurency/CQUI_Community-Edition#387]
**Describe the bug**
In multiplay mode without mod, the game won`t play wonder pop music and movie. We add this mod in multiplay mode, with the wonder pop music and movie option on. When wonder is finished, music and movie is forced start and I coud not  click any button, except using ESC button to system menu and back to main menu.

**To Reproduce**
1. Start a multiplay game with the wonder pop music and movie option on
2. Finish a wonder
3. See error

**General informations**
- OS: Windows 10 64 bit
- Version 1.0.0.290
- Expansion: Rise and Fall
- Other mods: Prismatic - Color and Jersey Overhaul.

**Comment by nukeajs** [comment]
Ditto. Hangs every time in multiplayer.

To get around it, either disable the wonder popups in the CQUI options under the "popups" tab. However, this must be done on a per session basis (maybe a per save basis, not sure) or ...

To make the change permanently, make a copy of "cqui_settings.sql" and rename it "cqui_settings_local.sql" . Open cqui_settings_local.sql and change line 56 ("CQUI_WonderBuiltPopupVisual", 1) to ("CQUI_WonderBuiltPopupVisual", 0) . I also changed line 57 from 1 to 0 but that's probably not necessary because the issue is with the visual popups not being able to be closed, not the audio.

**Comment by ubereffect** [comment]
Issue still present with latest version of CQUI posted on GitHub yesterday.

To be clear, I encountered this same issue while completing a wonder in single player. I had to hit escape, and reload from last auto-save. I then disabled the movie in the CQUI options, while keeping the audio enabled. This allowed me to continue without further issue.

**Comment by ubereffect** [comment]
Seems to be [fixed](https://github.com/Azurency/CQUI_Community-Edition/issues/397#issuecomment-488686779). At least I no longer get this bug in single player.
