### ISSUE TITLE
Bug: City Attack Range not working

### ISSUE THREAD

**Issue by EitanBlumin** [Azurency/CQUI_Community-Edition#7]
When a city has an enemy unit in attack range and I click on the targeting icon, instead of the targeting interface, it brings up the city's construction interface.
Reloading the savegame seems to solve the problem, though.

**Comment by Azurency** [comment]
Yes indeed, there's a `UI.SelectCity(attackCity);` instead of the `UI.LookAtPlot(attackCity:GetX(), attackCity:GetY());` line 519 in `actionpanel.lua`.
I'll fix this 👍 . 
And we also need to check for the encampment like they said in the original mod issue https://github.com/CQUI-Org/cqui/issues/591#issuecomment-319198727

**Comment by Azurency** [comment]
I fixed this, and even added an improvement. Now when you select the target icon, you directly enter the city range attack interface, no need to click on the city banner icon.

I will try to push it on this here as soon as possible, for now it's on my dev repo.

**Comment by EitanBlumin** [comment]
Great, thanks! You're doing a great job!
